baseURL = 'https://sit-institute/'
languageCode = 'de-DE'
title = 'sit.institute GmbH'
theme = "coming-soon"

[params]
    title = "sit.institute" 
    description = ""
    release = "Nov 1, 2025"
    favicon = ""
    message = "" 
    background = ""

socialIcons = [
    {name = "email", url = "info@sit.institute"},
    {name = "cal", url = "https://sit.institute/kennenlernen"},
    {name = "github", url = "https://github.com/sit-institute"},
    {name = "linkedin", url = "https://linkedin.com/company/sit-institute"},
] 
